# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set database password
        env:
          SECRETS_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        run: echo "database_password=$SECRETS_PASSWORD" | cat >> ./src/main/resources/application.properties
        
      - name: Build jar
        run: ./gradlew bootJar
        
      - name: Deploy to PWS
        env:
          CF_API_ENDPOINT: api.cf.eu10.hana.ondemand.com
          ORG: 0deefb8etrial
          SPACE: dev
          USERNAME: ${{ secrets.CF_USERNAME }}
          PASSWORD: ${{ secrets.CF_PASSWORD }}
          APP_NAME: rekoderback
          ARTIFACT_PATH: build/libs/rekoder-0.0.1-SNAPSHOT.jar
        run: |
          wget 'https://packages.cloudfoundry.org/stable?release=debian64&version=7.2.0&source=github-rel' -O package.deb
          sudo apt-get install ./package.deb
          cf login -a $CF_API_ENDPOINT -o $ORG -s $SPACE -u $USERNAME -p $PASSWORD
          cf push $APP_NAME -p $ARTIFACT_PATH -b https://github.com/cloudfoundry/java-buildpack.git
